version: "3.7"
services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: youremail@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"
    volumes:
      - pgadm-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  database-data:
  pgadm-data: